module GlobalConstants

  @all = "Alex Haas,https://github.com/haasalex16/CapstoneProject,|,Brian Kang,https://github.com/Kayleith/shutter-step,|,Charles Chen,https://github.com/chalzstrassen/Capstone-Project,|,Dylan Nelson,https://github.com/dylanonelson/medium_spare,|,Emmanuel Genard,https://github.com/edgenard/study_two,|,Eric Firth,https://github.com/ericfirth/quack-app,|,Eric Savadian,https://github.com/slancio/meeplespace,|,Felicia Wong,https://github.com/quixotically/Airfnf,|,Harris Jordan,https://github.com/wjordan213/BetterNote,|,Jeremy Lilly,https://github.com/giovanni-da-rumore/cicadas-song,|,Jose Garza,https://github.com/minutetominute/mysuperheropal,|,Konrad Dudziak,https://github.com/lonewarrior556/capstone-project,|,Liann Sun,https://github.com/lisunshiny/welp,|,Lily Riopelle,https://github.com/lilyriopelle/cooking_genius/,|,Lily Zhang,https://github.com/lilyxl8/leppo,|,Nathan Hinchey,https://github.com/nathanhinchey/okcupid_clone,|,Rhoen Pruesse-Adams,https://github.com/rhoen/nycBNB,|,Sung Jin Kim,https://github.com/sjkim24/questiontoallanswers,|,Thomas Jenkins,https://github.com/Arcane52689/Classic-Car-Classifieds/,|,Thomas Paresi,https://github.com/tparesi/product-hunt".gsub(",|,","|")


  ALL_PROJECTS = @all.split("|").map{|a| a.split(",")}

  SEED_LINKS = "http://wiki.answers.com/Q/Where_was_1953_film_noir_%27City_That_Never_Sleeps%27_shot
  http://www.answers.com/Q/How_do_you_identify_existing_wiring_in_an_older_building
  http://www.answers.com/Q/Where_can_a_new_repo_company_find_insurance
  http://www.answers.com/Q/What_is_the_history_of_the_Block_Island_Ferry
  http://www.answers.com/Q/What_was_the_incident_in_a_New_York_factory_that_burned_to_death_hundreds_of_women
  http://www.answers.com/Q/What_was_it_like_to_live_in_New_York_City_in_the_1950s
  http://www.answers.com/Q/Who_colonized_New_York_City
  http://wiki.answers.com/Q/What_sort_of_government_did_New_York_have_in_the_early_1700%27s
  http://www.answers.com/Q/What_is_the_history_of_the_New_York_subway_musicians
  http://www.answers.com/Q/Why_was_New_York_Founed
  http://wiki.answers.com/Q/What_were_the_demographics_of_colonial_1700%27s_New_York
  http://wiki.answers.com/Q/Where_was_New_York%27s_Five_Points
  http://www.answers.com/Q/Was_the_geography_of_New_York_different_when_the_Dutch_settled_it
  http://www.answers.com/Q/When_was_the_first_taxi_in_New_York_City
  http://www.answers.com/Q/Who_did_Mayor_John_Lindsay_defeat_when_he_ran_for_Mayor_of_New_York_City_in_1965_1969_and_1971
  http://www.answers.com/Q/When_was_New_York_originally_settled
  http://www.answers.com/Q/How_did_NYC_get_the_nickname_Gotham
  http://www.answers.com/Q/What_was_New_York_City_like_during_World_War_2
  http://www.answers.com/Q/What_are_the_different_boroughs_of_New_York
  http://www.answers.com/Q/Was_New_York_City_the_capital_of_United_States_and_if_so_when
  http://www.answers.com/Q/What_was_the_original_name_of_New_York_City
  http://wiki.answers.com/Q/Where_can_you_find_a_list_of_all_of_New_York_City%27s_mayors
  http://www.answers.com/Q/Was_Central_Park_always_closed_to_traffic
  http://www.answers.com/Q/How_and_why_was_New_Amsterdam_founded
  http://www.answers.com/Q/When_did_New_York_become_a_state
  http://www.answers.com/Q/How_do_you_find_US_immigration_records
  http://www.answers.com/Q/Who_was_father_of_Adam_Brouwer_Berkhoven_a_Dutch_West_Indies_soldier_who_settled_in_New_Amsterdam_in_1642
  http://www.answers.com/Q/How_many_restaurants_are_in_Manhattan
  http://www.answers.com/Q/What_are_the_5_borough_of_New_York_City
  http://www.answers.com/Q/Where_is_the_best_place_to_sell_your_Grand_National_which_you_bought_new_and_has_everything_original_except_the_tires_and_exhaust
  http://www.answers.com/Q/Which_celebrities_performed_at_the_Apollo_Theater_in_New_York_before_becoming_famous
  http://www.answers.com/Q/Who_was_the_first_mayor_of_New_York_City
  http://www.answers.com/Q/What_is_the_best_time_for_Bahamas_travel
  http://www.answers.com/Q/Can_two_documented_immigrants_who_were_married_in_another_country_get_a_divorce_in_New_York_City
  http://www.answers.com/Q/Who_do_you_talk_to_about_moving_your_business_to_New_Orleans_for_work
  http://www.answers.com/Q/On_what_New_York_square_was_S_Klein_on_the_Square
  http://www.answers.com/Q/Where_can_you_buy_Hai_Karate_perfume_in_New_York
  http://www.answers.com/Q/What_was_the_name_of_the_first_settlement_in_New_York
  http://www.answers.com/Q/How_did_New_York_get_its_name
  http://www.answers.com/Q/What_are_zones_on_long_island_railroad
  http://www.answers.com/Q/How_does_a_railway_metro_work
  http://wiki.answers.com/Q/What_are_New_York%27s_major_landforms
  http://www.answers.com/Q/What_are_all_the_major_cities_in_New_York
  http://www.answers.com/Q/Which_group_was_settled_in_New_York
  http://www.answers.com/Q/How_does_a_minor_rent_an_apartment
  http://www.answers.com/Q/Where_can_you_buy_firewood_on_Long_Island
  http://www.answers.com/Q/How_far_is_Guam_from_New_York_City
  http://www.answers.com/Q/What_is_the_latitude_and_longitude_for_New_York_City_New_York
  http://www.answers.com/Q/Who_created_the_Tammany_hall_tiger
  http://www.answers.com/Q/Where_in_North_America_is_area_code_718
  http://www.answers.com/Q/Where_is_the_nearest_airport_from_Uniondale_NY
  http://www.answers.com/Q/What_is_the_New_York_City_pin_code
  http://www.answers.com/Q/How_many_restaurants_are_there_in_Manhattan
  http://www.answers.com/Q/Where_can_you_sell_plasma_in_New_York_City
  http://www.answers.com/Q/What_Terminal_at_JFK_is_Swiss_air
  http://www.answers.com/Q/1800_GMT_is_what_time_in_New_York_City
  http://wiki.answers.com/Q/Why_is_New_York_City_called_%27The_Big_Apple%27
  http://www.answers.com/Q/How_does_New_York_City_remove_snow
  http://www.answers.com/Q/Largest_buildings_in_New_York_City
  http://www.answers.com/Q/Is_Chinatown_dirty
  http://www.answers.com/Q/Hunger_in_New_York_City_Literary_Devices
  http://www.answers.com/Q/What_is_the_distance_around_Central_Park
  http://www.answers.com/Q/Does_LaGuardia_Airport_have_smoking_rooms
  http://www.answers.com/Q/Tania_is_writing_a_paper_for_her_history_teacher_about_living_conditions_of_immigrants_in_urban_tenements_during_the_19th_century_Which_of_the_following_sources_would_be_the_best_for_her_to_quote_in
  http://www.answers.com/Q/How_do_you_get_to_225_Cadman_Plaza_Brooklyn_NY_11201_on_the_subway
  http://www.answers.com/Q/What_subway_do_you_take_from_31st_Street_to_Grand_Central_Terminal
  http://www.answers.com/Q/At_what_time_will_the_sun_set_on_October_18_2010_in_New_York_City
  http://www.answers.com/Q/What_train_will_take_you_to_Rector_Street
  http://www.answers.com/Q/Where_can_you_buy_whiskey_in_new_york_city
  http://www.answers.com/Q/How_far_is_Greenwich_Village_from_Penn_Station
  http://www.answers.com/Q/What_is_the_distance_between_Battery_Park_and_the_Brooklyn_Bridge
  http://www.answers.com/Q/What_borough_is_laguardia_in
  http://www.answers.com/Q/Is_Penn_Station_close_to_Grand_Central_Station
  http://www.answers.com/Q/Where_did_Central_Park_get_its_name
  http://www.answers.com/Q/When_will_new_york_deer_go_into_rut_in_2010
  http://www.answers.com/Q/How_many_miles_from_New_Brunswick_NJ_to_New_York_City
  http://www.answers.com/Q/What_are_the_major_human_features_in_New_York_City
  http://www.answers.com/Q/How_much_does_it_cost_to_rent_a_Broadway_theater_for_a_week
  http://www.answers.com/Q/How_many_stamps_does_it_take_to_mail_a_letter_from_New_York_to_Afghanistan
  http://www.answers.com/Q/How_far_is_Green_Bay_from_New_York_city
  http://www.answers.com/Q/Do_you_say_the_street_or_avenue_first_in_Manhattan
  http://www.answers.com/Q/Is_there_a_train_from_John_F._Kennedy_to_Harlem
  http://www.answers.com/Q/Which_New_York_City_subway_lines_go_from_14th_Street_to_Penn_Station
  http://www.answers.com/Q/What_does_ishmael_like_about_New_York_City
  http://www.answers.com/Q/Where_can_you_buy_salvia_in_new_york_city
  http://www.answers.com/Q/Where_is_Ap_cargo_in_Pagadian_City
  http://www.answers.com/Q/Can_you_pick_up_the_N_train_at_Penn_Station
  http://www.answers.com/Q/What_is_the_shortest_New_York_City_street
  http://www.answers.com/Q/How_many_snow_plows_are_in_New_York_City
  http://www.answers.com/Q/Who_are_the_street_legends_in_NBA_Street
  http://www.answers.com/Q/Can_you_pick_up_the_D_train_at_Penn_Station
  http://www.answers.com/Q/How_many_teachers_work_in_new_york_city
  http://www.answers.com/Q/How_far_is_New_York_City_from_York_PA
  http://www.answers.com/Q/What_region_of_the_US_is_new_york_city_located
  http://www.answers.com/Q/How_much_is_a_taxi_from_John_F._Kennedy_to_Grand_Central_Station
  http://www.answers.com/Q/Can_you_own_a_pet_tiger_cub_in_new_york_state
  http://www.answers.com/Q/Was_the_pentagon_or_the_south_tower_hit_first
  http://www.answers.com/Q/How_can_you_go_to_26_Federal_Plaza_New_York_NY_by_the_D_train_from_Brooklyn
  http://www.answers.com/Q/Who_made_a_New_York_Armory_12_gauge_shotgun_and_when_was_it_made
  http://www.answers.com/Q/Where_can_you_find_a_cover_for_your_seatbelt_bolt_where_it_attaches_to_the_wall_by_the_door_on_a_2000_VW_Beetle
  http://www.answers.com/Q/When_was_Garfield_street_renamed_Dickens
  http://www.answers.com/Q/What_is_info_on_Madison_Garden_and_White_City_roller_rinks
  http://www.answers.com/Q/What_determines_if_a_Chicago_street_is_called_an_avenue_boulevard_place_road_or_street
  http://www.answers.com/Q/Are_there_repo_associations_you_can_join_and_learn_from
  http://www.answers.com/Q/What_was_the_original_Vermont_State_Hospital_used_for_and_when_was_it_built
  http://www.answers.com/Q/Who_was_Seaman_York
  http://www.answers.com/Q/When_was_New_York_founded
  http://www.answers.com/Q/Casinos_and_gambling_in_old_New_York
  http://wiki.answers.com/Q/What_was_imported_and_exported_through_New_York_in_the_1700%27s
  http://www.answers.com/Q/When_was_Grand_Central_Station_completed
  http://www.answers.com/Q/Were_the_guns_in_Battery_Park_ever_fired
  http://www.answers.com/Q/Why_do_the_manholes_steam_in_New_York
  http://www.answers.com/Q/Is_there_a_list_of_undertakers_in_New_York_City_during_the_Civil_War
  http://www.answers.com/Q/What_is_the_date_New_York_declared_its_independence
  http://wiki.answers.com/Q/What_industries_in_New_York_City_were_effected_by_cholera_in_the_late_1800%27s
  http://www.answers.com/Q/What_was_at_119_West_46th_Street_in_Manhattan_in_1923
  http://www.answers.com/Q/What_was_New_York_covered_with_when_the_explorers_arrived
  http://www.answers.com/Q/Where_did_the_name_Queens_come_from
  http://www.answers.com/Q/How_did_New_York_become_a_state
  http://www.answers.com/Q/What_were_the_reasons_for_the_founding_of_New_York
  http://www.answers.com/Q/Is_it_true_that_Canal_Street_in_New_York_City_is_named_because_it_lies_on_top_of_an_old_canal
  http://www.answers.com/Q/How_was_the_New_York_colony_formed
  http://www.answers.com/Q/What_was_life_like_for_children_in_New_Amsterdam_in_the_1600s
  http://www.answers.com/Q/Who_were_all_of_the_New_York_mayors_in_the_last_50_years
  http://www.answers.com/Q/How_long_was_the_New_York_Siegel_Cooper_department_store_in_business_and_how_did_it_compare_in_size_and_elegance_to_the_Chicago_store
  http://www.answers.com/Q/What_is_the_population_in_New_York_today
  http://www.answers.com/Q/What_is_the_history_of_the_Hotel_Chelsea_in_New_York
  http://www.answers.com/Q/What_is_the_state_bird_of_New_York
  http://www.answers.com/Q/What_is_the_state_flower_of_New_York
  http://www.answers.com/Q/Why_was_New_York_founded_in_1664
  http://www.answers.com/Q/Who_were_some_famous_people_from_New_York_City_in_the_1700s
  http://www.answers.com/Q/What_is_the_state_flag_of_New_York
  http://wiki.answers.com/Q/When_was_the_%27new%27_Waldorf_Astoria_opened_for_business
  http://www.answers.com/Q/Where_can_you_find_out_more_about_the_Brooklyn_Robins
  http://www.answers.com/Q/Where_can_you_find_information_about_Camp_Shank_New_York
  http://www.answers.com/Q/Where_would_you_get_parts_or_a_new_barrel_or_any_info_on_a_double_barrel_20_gauge_marked_American_Gun_Co._New_York_on_the_side
  http://www.answers.com/Q/Can_an_auto_lease_judgment_be_used_as_a_lien_against_your_home_in_the_state_of_New_York
  http://www.answers.com/Q/When_did_New_York_state_start_to_offer_associate_degrees
  http://www.answers.com/Q/Where_can_you_search_for_blueprints_of_generic_buildings
  http://www.answers.com/Q/Can_a_motorcycle_be_repossessed_from_a_closed_garage_in_New_York_City
  http://www.answers.com/Q/In_the_State_of_New_York_can_a_parent_make_their_17-year-old_pay_rent_if_they_are_claiming_the_minor_child_on_their_taxes
  http://www.answers.com/Q/What_rights_are_granted_to_you_in_New_York_state_when_you_turn_18
  http://www.answers.com/Q/Where_can_a_14-year-old_in_New_York_get_a_job
  http://www.answers.com/Q/Is_it_legal_for_a_licensed_bar_to_use_happy_hour_pull_tabs_in_New_York_State
  http://www.answers.com/Q/What_could_be_the_consequences_when_a_person_who_has_little_income_and_no_personal_property_is_sued_by_a_collection_agency_in_New_York_City
  http://www.answers.com/Q/How_do_you_put_a_lien_on_a_home_in_New_York_Kings_County
  http://www.answers.com/Q/How_much_is_a_12_gauge_American_Gun_Co_New_York_with_hammers_352596_matching_parts_be_worth
  http://www.answers.com/Q/What_happened_in_New_York_during_the_Revolutionary_War
  http://www.answers.com/Q/How_tall_is_the_Empire_State_Building
  http://www.answers.com/Q/Is_New_York_City_urban_or_rural
  http://www.answers.com/Q/Can_you_own_and_drive_a_hearse_in_New_York_City_if_you_do_not_work_for_a_funeral_home
  http://wiki.answers.com/Q/Should_you_buy_gun_for_ps2_or_true_crime%3Anyc
  http://www.answers.com/Q/How_old_do_you_have_to_be_to_move_out_in_New_York
  http://www.answers.com/Q/Aside_from_health_clubs_and_civic_groups_where_can_a_person_in_a_small_city_meet_someone_interested_in_dating
  http://www.answers.com/Q/What_is_the_Statue_of_Liberty_made_of
  http://www.answers.com/Q/Why_is_it_important_for_a_hotel_to_have_good_housekeeping_practices
  http://www.answers.com/Q/What_is_the_telephone_area_code_for_New_York_City
  http://www.answers.com/Q/How_do_you_obtain_a_replacement_marriage_certificate_asap_in_New_York_City
  http://www.answers.com/Q/How_did_New_Amsterdam_become_New_York
  http://www.answers.com/Q/Where_was_Robert_de_La_Salle_born
  http://www.answers.com/Q/What_cities_begin_with_the_letter_K
  http://www.answers.com/Q/How_far_is_Sarasota_FL_from_New_York_City
  http://www.answers.com/Q/Can_you_take_a_bus_from_NY_to_Alaska
  http://www.answers.com/Q/How_far_is_it_from_Brooklyn_to_SoHo
  http://www.answers.com/Q/How_do_you_become_a_Black-Cab_driver
  http://www.answers.com/Q/What_foods_is_New_York_known_for
  http://www.answers.com/Q/How_long_is_flight_from_new_york_city_to_Hanoi
  http://www.answers.com/Q/Where_is_the_closest_Amtrak_station_to_Phillipsburg_NJ
  http://www.answers.com/Q/What_did_the_Dutch_originally_call_Ellis_Island
  http://www.answers.com/Q/When_did_the_Chinese_immigrants_arrive_in_New_York_City
  http://www.answers.com/Q/What_does_New_York_mean_in_English
  http://www.answers.com/Q/How_many_miles_between_New_York_to_Alaska
  http://www.answers.com/Q/Are_there_any_Gangster_Disciples_in_New_York
  http://www.answers.com/Q/Which_supermarket_on_long_island_sells_bovril
  http://www.answers.com/Q/Is_there_bus_service_from_New_York_City_to_attica_correctional_facility
  http://wiki.answers.com/Q/Where_is_Nickelodeon%27s_Worldwide_Day_of_Play_2010_in_New_York_City_taking_place
  http://www.answers.com/Q/How_long_does_it_take_for_a_letter_to_arrive_from_New_York_to_Argentina
  http://www.answers.com/Q/How_far_is_penn_station_to_south_ferry
  http://www.answers.com/Q/What_city_is_halfway_point_between_New_York_and_Texas
  http://www.answers.com/Q/What_subway_do_you_take_from_Rockefeller_Center_to_Little_Italy
  http://www.answers.com/Q/How_many_died_building_the_World_Trade_Center
  http://www.answers.com/Q/How_far_is_Penn_Station_from_the_Shubert_Theater
  http://www.answers.com/Q/What_subway_do_you_take_from_Penn_Station_to_Chambers_Street
  http://www.answers.com/Q/Which_subway_do_you_take_from_Penn_Station_to_SoHo
  http://www.answers.com/Q/What_train_will_take_you_to_Bleecker_street
  http://www.answers.com/Q/Which_subway_do_you_take_from_Port_Authority_to_SoHo
  http://www.answers.com/Q/How_do_you_get_to_Mott_Street_from_Penn_Station_NY
  http://www.answers.com/Q/Do_New_York_City_subways_travel_underwater
  http://www.answers.com/Q/What_is_the_zip_code_for_1211_Avenue_of_the_Americas
  http://www.answers.com/Q/How_many_miles_can_you_see_from_the_world_trade_center_tower
  http://www.answers.com/Q/How_thick_is_a_new_york_city_phone_book
  http://www.answers.com/Q/How_go_you_get_from_Penn_Station_to_Mulberry_Street
  http://www.answers.com/Q/Where_was_the_the_World_Trade_Center_located_exactly_in_New_York
  http://www.answers.com/Q/When_did_Ellis_Island_stop
  http://wiki.answers.com/Q/How_do_you_get_into_the_Macy%27s_Thanksgiving_Day_Parade
  http://www.answers.com/Q/What_subway_do_you_take_from_Penn_Station_to_70th_Street
  http://wiki.answers.com/Q/How_do_you_walk_from_Macy%27s_to_the_World_Trade_Center
  http://www.answers.com/Q/How_much_do_greyhound_bus_tickets_from_California_to_Phoenix_Arizona
  http://www.answers.com/Q/Where_can_you_buy_new_custom_products_for_a_1973_Dodge_D100_truck
  http://www.answers.com/Q/Who_was_Rush_Street_named_after
  http://www.answers.com/Q/What_is_the_name_and_history_of_the_abandoned_church_right_next_to_the_cooking_school_and_directly_across_from_the_Cabrini_Green_Housing_Projects
  http://www.answers.com/Q/Can_a_college_student_with_a_Florida_license_drive_a_family_owned_car_insured_in_Florida_while_going_to_school_in_New_York
  http://www.answers.com/Q/Would_a_14-year-old_be_able_to_move_out_and_live_on_her_own_in_New_York_state_if_she_is_pregnant
  http://www.answers.com/Q/Do_you_have_to_shock_a_brand_new_easy_set_vinyl_pool_just_filled_for_the_first_time_with_city_water_before_you_can_swim
  http://www.answers.com/Q/When_did_New_York_enter_the_us
  http://www.answers.com/Q/Where_could_you_find_a_map_on_the_development_of_New_York_city_as_a_site
  http://www.answers.com/Q/What_was_the_major_crop_in_New_York_in_the_late_1700s
  http://www.answers.com/Q/What_were_the_4_colonies_made_from_New_York
  http://www.answers.com/Q/Why_is_New_York_so_popular_for_tourists
  http://www.answers.com/Q/Who_is_the_mayor_of_New_York_City
  http://www.answers.com/Q/Who_was_the_mayor_of_New_York_City_at_the_time_of_the_1939_World_Fair
  http://www.answers.com/Q/When_was_the_Biltmore_Hotel_once_across_the_street_and_just_south_of_Grand_Central_Station_built_and_when_was_it_demolished
  http://www.answers.com/Q/What_is_the_history_of_FDNY_Engine_79_in_the_Bronx
  http://www.answers.com/Q/How_did_rich_and_poor_people_live_in_19th_century_New_York_City
  http://www.answers.com/Q/How_did_Idlewild_Airport_get_its_name
  http://www.answers.com/Q/Since_Idlewild_Airport_was_named_after_the_Idlewild_Golf_Course_where_did_the_name_Idlewild_come_from_initially
  http://www.answers.com/Q/How_was_New_York_settled
  http://wiki.answers.com/Q/How_was_the_street_name_%27Broadway%27_derived_and_what_is_the_history_behind_this_contorted_line_going_down_Manhattan
  http://www.answers.com/Q/When_was_the_World_Trade_Center_built
  http://www.answers.com/Q/Who_were_the_first_people_to_settle_in_New_York_and_what_was_their_life_style_like
  http://www.answers.com/Q/How_was_the_legislature_elected_in_colonial_New_York_State_and_how_much_authority_was_the_legislature_given
  http://wiki.answers.com/Q/What_trains_were_running_between_Montreal_and_New_York_City_in_the_1870%27s_and_1880%27s
  http://www.answers.com/Q/How_many_people_were_killed_in_the_Twin_Towers
  http://www.answers.com/Q/Why_was_the_gridiron_street_plan_implemented_in_New_York
  http://www.answers.com/Q/Why_was_New_York_named_after_James_Duke_Of_York
  http://www.answers.com/Q/How_did_the_Dutch_population_in_New_York_influence_the_way_people_live_today_in_New_York_State
  http://www.answers.com/Q/Why_is_Long_Island_was_not_included_as_a_borough_of_New_York
  http://www.answers.com/Q/Was_New_York_City_built_on_swamp_ground
  http://www.answers.com/Q/What_are_the_temperatures_for_New_York_in_summer_and_winter
  http://www.answers.com/Q/What_are_the_different_Boroughs_famous_for
  http://wiki.answers.com/Q/What_was_New_York%27s_population_geography_size_industry_economy_culture_and_slave_population_during_the_1600s_and_1700s
  http://www.answers.com/Q/How_big_is_New_York_City_in_square_miles
  http://wiki.answers.com/Q/When_did_the_Macy%27s_Thanksgiving_Parade_stop_being_a_parade_and_became_a_time_for_various_corporate-network_promotions_and_sideshow_acts
  http://www.answers.com/Q/How_long_would_you_have_to_serve_in_jail_for_breaking_into_a_high_school_facility
  http://www.answers.com/Q/Where_is_the_02_sensor_on_a_1988_Chrysler_Fifth_Avenue
  http://www.answers.com/Q/What_was_the_old_name_of_New_York_City
  http://www.answers.com/Q/Is_a_penny_with_two_heads_one_horizontal_and_one_vertical_and_the_same_for_the_building_on_the_back_worth_anything
  http://www.answers.com/Q/What_is_the_most_famous_New_York_mafia
  http://www.answers.com/Q/What_year_was_New_York_established
  http://www.answers.com/Q/How_do_you_take_the_windshield_screws_out_on_a_1994_wrangler
  http://www.answers.com/Q/If_you_lived_in_New_York_for_seven_years_on_F1_and_H1_visas_and_then_left_the_country_owing_65K_in_debt_what_would_happen_to_you_if_you_now_return_to_New_York
  http://www.answers.com/Q/Why_is_Marble_Hill_part_of_the_borough_of_Manhattan
  http://www.answers.com/Q/How_do_you_fix_a_hesitating_engine_cold_or_warmed_up_1988_Chrysler_Fifth_Avenue
  http://wiki.answers.com/Q/Was_any_part_of_New_York%27s_land_man_made
  http://www.answers.com/Q/What_is_the_State_motto_of_New_York
  http://www.answers.com/Q/What_city_is_200_miles_west_of_Hudson_Ohio
  http://www.answers.com/Q/What_is_the_name_of_the_woman_in_the_dockers_commercial_where_they_are_riding_in_street_cars
  http://www.answers.com/Q/How_does_a_building_section_help_in_analyzing_a_street
  http://www.answers.com/Q/How_should_you_start_planning_a_move_to_a_new_city
  http://www.answers.com/Q/What_is_the_average_weather_in_New_York_City_around_June
  http://www.answers.com/Q/How_many_people_live_in_New_York
  http://www.answers.com/Q/What_is_the_population_of_New_York_City
  http://www.answers.com/Q/Why_was_New_York_founded
  http://www.answers.com/Q/Who_is_the_Brooklyn_Brawler
  http://www.answers.com/Q/Is_the_Ritz_Carlton_Hotel_in_San_Juan_a_new_hotel_or_an_old_hotel_with_a_new_name
  http://wiki.answers.com/Q/Why_are_the_Scarborough_Town_Centre_and_McCowan_in_the_TTC%27s_SRT_if_the_stations_are_3_min._walk_apart_3_bus_routes_stop_at_both_stations_Scarborough_also_has_elevators_parking_and_a_bus_terminal
  http://www.answers.com/Q/What_is_the_walking_distance_between_howard_beach_station_and_John_F._Kennedy_airport_terminal_1
  http://www.answers.com/Q/What_is_the_history_behind_the_milford_plaza_hotel_in_new_york
  http://www.answers.com/Q/What_is_the_Empire_State_Building_used_for
  http://www.answers.com/Q/What_Henry_James_novel_shares_its_name_with_a_Manhattan_park
  http://www.answers.com/Q/Time_difference_between_Athens_Greece_and_New_York
  http://www.answers.com/Q/Is_Grand_Central_Station_connected_to_Penn_Station_by_a_subway_or_shuttle
  http://www.answers.com/Q/How_many_DIY_buffs_does_it_take_to_screw_in_a_light_bulb
  http://www.answers.com/Q/How_many_recovering_addicts_does_it_take_to_screw_in_a_light_bulb
  http://www.answers.com/Q/Is_there_parking_at_the_greyhound_bus_station_in_Buffalo_NY
  http://www.answers.com/Q/How_to_train_a_watchdog
  http://www.answers.com/Q/What_stores_are_in_the_Randall_Park_Mall
  http://www.answers.com/Q/How_many_blocks_equal_a_mile_in_Salt_Lake_City
  http://www.answers.com/Q/At_what_age_are_you_considered_an_adult_in_New_York_State
  http://www.answers.com/Q/Where_can_you_buy_reflective_croc_city_series_air_force_ones_in_New_York_city
  http://www.answers.com/Q/What_is_the_most_expensive_department_store_in_Manhattan
  http://www.answers.com/Q/What_would_economists_describe_the_US_automobile_industry_as
  http://www.answers.com/Q/How_far_is_New_York_City_to_manhasset
  http://www.answers.com/Q/Distance_New_York_City_to_Harrisburg_PA
  http://www.answers.com/Q/Is_Roosevelt_Island_part_of_Manhattan
  http://www.answers.com/Q/Why_is_New_York_called_the_metal_lands
  http://www.answers.com/Q/How_far_Manchester_New_York_to_New_York_City
  http://www.answers.com/Q/How_much_gas_you_spend_from_Miami_to_New_York
  http://www.answers.com/Q/How_many_city_blocks_would_you_have_to_walk_back_if_you_walked_8_blocks_east_then_3_blocks_North_and_then_finished_by_walking_4_blocks_west
  http://www.answers.com/Q/How_many_Mexicans_live_in_New_York_City
  http://wiki.answers.com/Q/Is_New_York_City%27s_water_hard_or_soft
  http://www.answers.com/Q/What_strait_connects_Upper_New_York_Bay_to_Lower_New_York_Bay
  http://www.answers.com/Q/Who_sponsors_the_annual_Thanksgiving_Day_Parade_in_New_York_City
  http://wiki.answers.com/Q/How_is_Manhattan%27s_street_layout_organised
  http://www.answers.com/Q/How_much_snow_is_on_the_ground_in_New_York_City
  http://www.answers.com/Q/Are_steel_batons_illegal_to_carry_in_PA
  http://www.answers.com/Q/How_long_to_drive_from_New_Jersey_to_new_york_city
  http://www.answers.com/Q/What_train_takes_you_to_26_Federal_Plaza_from_Penn_Station
  http://www.answers.com/Q/Where_is_the_real_Central_Perk_in_New_York
  http://www.answers.com/Q/Is_Liberty_City_in_New_York_or_in_New_York_City
  http://www.answers.com/Q/What_time_does_summer_school_starts_in_new_york_city
  http://www.answers.com/Q/What_subway_train_stops_near_the_Queens_Center_Mall
  http://www.answers.com/Q/How_many_miles_form_Binghamton_NY_to_New_York_NY
  http://www.answers.com/Q/Which_city_is_the_furthest_from_Manchester_England_New_York_Berlin_Paris_or_LA
  http://www.answers.com/Q/How_many_air_miles_from_Seattle_to_New_York_city
  http://www.answers.com/Q/How_do_you_change_the_day_on_shopaholic_New_York
  http://www.answers.com/Q/Who_owns_Central_Park
  http://www.answers.com/Q/How_long_does_ups_ground_take_from_Los_Angeles_to_New_York_City".gsub(" ","").split("\n")

  def extract_title(body)
    start = body.index('<span class="title_text">') + '<span class="title_text">'.length
    fin = body.index('</span>',start)
    return body[start...fin]
  end

  def extract_replies(body)
    regex = /<b>[^<][\n]*.*nswer.*<\/b>/
    start = body.index('<div class="answer_text">') + '<div class="answer_text">'.length
    fin = body.index('</div>',start)
    all_answers = body[start...fin]
    all_answers = all_answers.gsub("<br />","").gsub(regex,"PPqq,z,qqPP")
    all_answers.split("PPqq,z,qqPP").select{|a| a.gsub(" ","").length > 5 }
  end




end
